package com.bansheegz.copyright;

import java.io.File;
import java.io.FileFilter;
import java.io.IOException;
import java.nio.file.Files;
import java.nio.file.StandardOpenOption;
import java.util.ArrayList;
import java.util.List;

public class CopyRighter
{
    private final String copyright;
    private File dir;
    private List<String> ignoreNames = new ArrayList<>();

    public CopyRighter(File dir)
    {
        this.dir = dir;
        copyright = "/*\n" +
                "<copyright file=\"__file__\" company=\"BansheeGz\">\n" +
                "    Copyright (c) 2018 All Rights Reserved\n" +
                "</copyright>\n" +
                "*/\n";

        ignoreNames.add("SimpleJSON.cs");
    }

    public static void main(String[] args) throws Exception
    {
        if (args == null || args.length != 1)
        {
            throw new Exception("Provide the root directory");
        }
        File dir = new File(args[0]);

        if (!dir.exists())
        {
            throw new Exception("Can not find file " + dir.getAbsolutePath());
        }

        if (!dir.isDirectory())
        {
            throw new Exception("File is not folder" + dir.getAbsolutePath());
        }
        new CopyRighter(dir).process();
    }

    private void process() throws IOException
    {
        process(dir);
    }

    private void process(File dir) throws IOException
    {
        File[] sharpSource = dir.listFiles(pathname -> pathname.getName().endsWith(".cs"));
        if (sharpSource != null)
        {
            for (File file : sharpSource)
            {
//                System.out.println("Found source: " + file.getAbsolutePath());
                processSource(file);
            }
        }
        File[] subfolders = dir.listFiles(File::isDirectory);
        if (subfolders != null)
        {
            for (File subfolder : subfolders) process(subfolder);
        }
    }

    private void processSource(File file) throws IOException
    {
        String content = new String(Files.readAllBytes(file.toPath()));
        if (content.contains("//||                   Generated by BansheeGz Code Generator ||\r\n")) return;

        if (ignoreNames.contains(file.getName())) return;

        String s = "<copyright file=\"";
        int index = content.indexOf(s);
        if (index==-1)
        {
                String myCopyright = copyright.replaceFirst("__file__", file.getName());
                content = myCopyright + content;
                Files.write(file.toPath(), content.getBytes(), StandardOpenOption.WRITE);
        }
        else
        {
            int startIndex = index + s.length();
            int endIndex = content.indexOf("\"", startIndex + 1);
            if(endIndex-startIndex>60) throw new IOException("max file name is exceeded: max=40 symbols, found " +(endIndex-startIndex) + " file " + file.getAbsolutePath() );
            String fileName = content.substring(startIndex, endIndex);
            if(!file.getName().equals(fileName))
            {
                content = content.substring(0,startIndex) + file.getName() + content.substring(endIndex);
                Files.write(file.toPath(), content.getBytes(), StandardOpenOption.WRITE);
            }
        }
    }
}
