package com.bansheegz.copyright;

import java.io.File;
import java.io.FileFilter;
import java.io.IOException;
import java.nio.charset.StandardCharsets;
import java.nio.file.Files;
import java.nio.file.StandardOpenOption;
import java.util.ArrayList;
import java.util.List;

public class CopyRighter
{
    private final String copyright;
    private File dir;
    private List<String> ignoreNames = new ArrayList<>();

    public CopyRighter(File dir)
    {
        this.dir = dir;
        copyright = "/*\n" +
                "<copyright file=\"__file__\" company=\"BansheeGz\">\n" +
                "    Copyright (c) 2018-2020 All Rights Reserved\n" +
                "</copyright>\n" +
                "*/";

        ignoreNames.add("SimpleJSON.cs");
        ignoreNames.add("LiteCsvParser.cs");
        ignoreNames.add("BGBSAStuff.cs");
    }

    public static void main(String[] args) throws Exception
    {
        if (args == null || args.length != 1)
        {
            throw new Exception("Provide the root directory");
        }
        File dir = new File(args[0]);

        if (!dir.exists())
        {
            throw new Exception("Can not find file " + dir.getAbsolutePath());
        }

        if (!dir.isDirectory())
        {
            throw new Exception("File is not folder" + dir.getAbsolutePath());
        }
        new CopyRighter(dir).process();
    }

    private void process() throws IOException
    {
        process(dir);
    }

    private void process(File dir) throws IOException
    {
        File[] sharpSource = dir.listFiles(pathname -> pathname.getName().endsWith(".cs"));
        if (sharpSource != null)
        {
            for (File file : sharpSource)
            {
//                System.out.println("Found source: " + file.getAbsolutePath());
                processSource(file);
            }
        }
        File[] subfolders = dir.listFiles(File::isDirectory);
        if (subfolders != null)
        {
            for (File subfolder : subfolders) process(subfolder);
        }
    }

    private void processSource(File file) throws IOException
    {
        String content = Files.readString(file.toPath(), StandardCharsets.UTF_8);
        if (content.contains("//||                   Generated by BansheeGz Code Generator ||\r\n")) return;

        if (ignoreNames.contains(file.getName())) return;

        String myCopyright = copyright.replaceFirst("__file__", file.getName());
        String s = "<copyright file=\"";
        int index = content.indexOf(s);
        if (index == -1)
        {
            //no copyright
            content = myCopyright +"\n" + content;
            Files.writeString(file.toPath(), content, StandardCharsets.UTF_8, StandardOpenOption.WRITE);
        } else
        {
            //check
/*
            int startIndex = index + s.length();
            int endIndex = content.indexOf("\"", startIndex + 1);
            if(endIndex-startIndex>60) throw new IOException("max file name is exceeded: max=60 symbols, found " +(endIndex-startIndex) + " file " + file.getAbsolutePath() );
            String fileName = content.substring(startIndex, endIndex);
            if(!file.getName().equals(fileName))
            {
                content = content.substring(0,startIndex) + file.getName() + content.substring(endIndex);
            }
*/

            if (!content.contains(myCopyright))
            {
                final String startToken = "/*";
                int startIndex = content.substring(0, index).indexOf(startToken);
                if (startIndex == -1) throw new RuntimeException("Unable to find start index for copyright. file= " + file.toPath());
                if (startIndex >10) throw new RuntimeException("Unable to find start index for copyright startIndex exceeded max value. file= " + file.toPath());

                final String endToken = "*/";
                int endIndex = content.indexOf(endToken, startIndex);
                if (endIndex == -1) throw new RuntimeException("Unable to find end index for copyright. file= " + file.toPath());
                if (endIndex - startIndex > 200) throw new RuntimeException("Max range for end index is exceeded for copyright. file= " + file.toPath());

                String postfix = content.substring(endIndex + endToken.length());
//                String prefix = content.substring(0, startIndex);
                String result = myCopyright + postfix;

                Files.writeString(file.toPath(), result, StandardCharsets.UTF_8, StandardOpenOption.CREATE);
            }
        }
    }
}
